trigger:
- master

pool:
  name: Default

stages:
  - stage: Build
    displayName: nameusedinUI-build
    jobs: 
      - job: Buildjob
        displayName: nameusedinUI-buildjob
        steps:
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
               Write-Host "Hello World"

  - stage: Deploy
    displayName: nameusedinUI-deploy
    jobs:
      - deployment: Deployjob
        displayName: nameusedinUI-deployjob
        environment: String 
        strategy:
         runOnce: 
          deploy:
            steps:
             - task: PowerShell@2
               inputs:
                targetType: 'inline'
                script: |
                 Write-Host "Hello World"

  - stage: Test
    displayName: nameusedinUI-test
    jobs:
      - job: Testjob
        displayName: nameusedinUI-testjob
        steps:
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
               Write-Host "Hello World"
