trigger:
- master

pool:
  name: Default

stages:
  - stage: Build
    displayName: nameusedinUI-build
    jobs: 
      - job: Buildjob
        displayName: nameusedinUI-buildjob
        steps:
        - task: AzureCLI@2
          inputs:
            azureSubscription: 'Free Trial(21ffa5d8-e7c7-481b-8a23-e5f94872f1fd)'
            scriptType: 'ps'
            scriptLocation: 'inlineScript'
            inlineScript: |
                  az acr login --name ACRlearning
                  docker login ACRlearning
                  docker build -t nginx . 
                  docker push ACRlearning.azurecr.io/nginx

  - stage: Deploy
    displayName: nameusedinUI-deploy
    jobs:
      - deployment: Deployjob
        displayName: nameusedinUI-deployjob
        environment: String 
        strategy:
         runOnce: 
          deploy:
            steps:
             - task: PowerShell@2
               inputs:
                targetType: 'inline'
                script: |
                 Write-Host "Hello World"

  - stage: Test
    displayName: nameusedinUI-test
    jobs:
      - job: Testjob
        displayName: nameusedinUI-testjob
        steps:
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
               Write-Host "Hello World"
