trigger:
- master

pool:
  name: Default

stages:
  - stage: Build
    displayName: nameusedinUI-build
    jobs: 
      - job: Buildjob
        displayName: nameusedinUI-buildjob
        continueOnError: false
        steps:
          - script: 'Write-Host "hello world!'
  - stage: Test
    displayName: nameusedinUI-test
    dependsOn: Build
    jobs:
      - job: Testjob
        displayName: nameusedinUI-testjob
        continueOnError: false
        steps:
          - script: 'Write-Host "hello world!'
  - stage: Deploy
    displayName: nameusedinUI-deploy
    dependsOn: Test
    jobs:
      - job: Deployjob
        displayName: nameusedinUI-deployjob
        steps:
          - script: 'Write-Host "hello world!'
