trigger:
- master

pool:
  name: Default

stages:
  - stage: Build
    displayName: nameusedinUI-build
    jobs: 
      - job: Build
        displayName: nameusedinUI-buildjob
        continueOnError: false
        steps:
          - script: 'Write-Host "hello world!'
  - stage: Test
    displayName: nameusedinUI-test
    dependsOn: Build
    jobs:
      - job: Test
        displayName: nameusedinUI-testjob
        continueOnError: false
        steps:
          - 
  - stage: Deploy
    displayName: nameusedinUI-deploy
    dependsOn: 
    jobs:
      - deployment: Deploy
        displayName: nameusedinUI-deployjob
        environment: # target environment name and optionally a resource name to record the deployment history; format: <environment-name>.<resource-name> strategy:

