trigger:
- master

pool:
  name: Default

stages:
  - stage: Build
    displayName: nameusedinUI-build
    jobs: 
      - job: Buildjob
        displayName: nameusedinUI-buildjob
        continueOnError: false
        steps:
          - script: 'Write-Host "hello world!'
  - stage: Test
    displayName: nameusedinUI-test
    dependsOn: Build
    jobs:
      - job: Testjob
        displayName: nameusedinUI-testjob
        continueOnError: false
        
  - stage: Deploy
    displayName: nameusedinUI-deploy
    dependsOn: Test
    jobs:
      - deployment: Deployjob
        displayName: nameusedinUI-deployjob
        environment: # target environment name and optionally a resource name to record the deployment history; format: <environment-name>.<resource-name> strategy:

