trigger:
- master

pool:
  name: Default

stages:
  - stage: Build
    displayName: Build Stage
    jobs: 
      - job: Buildjob
        displayName: Build Stage - Job.1
        continueOnError: false
        steps:
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: |
              docker build -t acrlearning.azurecr.io/nginx:$(Build.BuildNumber) C:\agents\_work\1\s
              docker push acrlearning.azurecr.io/nginx:$(Build.BuildNumber)
        - task: AzureCLI@2
          inputs:
            azureSubscription: 'Free Trial(21ffa5d8-e7c7-481b-8a23-e5f94872f1fd)'
            scriptType: 'ps'
            scriptLocation: 'inlineScript'
            inlineScript: |
                  az acr login -n ACRlearning
          
  - stage: Deploy
    displayName: Deployment Stage
    jobs:
      - deployment: DeploymentJob
        displayName: Deployment Stage - Job.1
        dependsOn: Build
        continueOnError: false
        environment: String 
        strategy:
         runOnce: 
          deploy:
            steps:
             - task: AzureCLI@2
               inputs:
                azureSubscription: 'Free Trial(21ffa5d8-e7c7-481b-8a23-e5f94872f1fd)'
                scriptType: 'ps'
                scriptLocation: 'inlineScript'
                inlineScript: |
                    az acr login -n ACRlearning --expose-token
                    az container create --resource-group 123 --name acinstance --image acrlearning.azurecr.io/nginx:$(Build.BuildNumber) --ports 80 --dns?

  - stage: Test
    displayName: Testing Stage
    jobs:
      - job: Testingjob
        displayName: Testing Stage - Job.1
        dependsOn: Deploy
        steps:
        - task: AzureCLI@2
          inputs:
                azureSubscription: 'Free Trial(21ffa5d8-e7c7-481b-8a23-e5f94872f1fd)'
                scriptType: 'ps'
                scriptLocation: 'inlineScript'
                inlineScript: |
                    $reply = invoke-webrequest site?..
                    $reply.statuscode